spring.application.name=banking-app

#database properties
spring.datasource.url=jdbc:mysql://localhost:3306/banking
spring.datasource.username=root
spring.datasource.password=Asif@123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update